trigger:
- main

pool:
  name: PoC IBK

steps:

- task: CmdLine@2
  inputs:
    script: |
      cd C:\Program Files\IBM\ACE\12.0.6.0\server\bin\
      
      mqsiprofile.cmd
      
      echo "funciona?"