trigger:
- main

pool:
  name: PoC IBK

steps:

- task: CmdLine@2
  inputs:
    script: |
      cd C:\Program Files\IBM\ACE\12.0.6.0
      
      ace.cmd
      mqsicreateworkdir --help
      echo holi
- task: CmdLine@2
  inputs:
    script: |
      cd "C:\Users\001664815\agent\_work\_temp\6c42c186-2e8b-492f-bf00-afbf67601cad.cmd
      mqsicreateworkdir --help
      echo holi