trigger:
- main

pool:
  name: PoC IBK
parameters:
  - ace
steps:

- task: CmdLine@2
  inputs:
    script: |
    CALL $ace
    echo "holi"

- task: CmdLine@2
  inputs:
    script: 'mqsicreateworkdir --help'
