trigger:
- main

pool:
  name: PoC IBK
parameters:
  - name: ace
steps:

- task: CmdLine@2
  inputs:
    script: |
      cd C:\Program Files\IBM\ACE\12.0.6.0
      CALL ace.cmd mqsicreateworkdir %TEMP%\\ace-server


