trigger:
- main

pool:
  name: PoC IBK
parameters:
  - name: ace
steps:

- task: CmdLine@2
  inputs:
    script: 'CALL C:\Program Files\IBM\ACE\12.0.6.0\ace.cmd mqsicreateworkdir %TEMP%\\ace-server'


