trigger:
- main

pool: 
  name: PoC IBK

steps:
  - task: CmdLine@2
    displayName: "Creating bar file"
    inputs:
      script: |
        CALL "C:\Program Files\IBM\ACE\12.0.6.0\ace.cmd" ibmint package --input-path $(system.defaultworkingdirectory)\ace-projects  --project simple-demo --output-bar-file $(system.defaultworkingdirectory)\templates\assets\api.bar
        
        echo "BAR file created"
  - task: CmdLine@2
    displayName: "Creating bar file with tests"
    inputs:
      script: |
        CALL "C:\Program Files\IBM\ACE\12.0.6.0\ace.cmd" ibmint package --input-path $(system.defaultworkingdirectory)\ace-projects  --project simple-demo_Test --output-bar-file $(system.defaultworkingdirectory)\templates\assets\api_Test.bar
        
        echo "BAR file with tests created"

  - task: CmdLine@2
    displayName: "Installing bars into test server"
    inputs:
      script: |
        CALL "C:\Program Files\IBM\ACE\12.0.6.0\ace.cmd" mqsibar --working-directory $(system.defaultworkingdirectory)\ace-projects\TEST_SERVER --bar-file $(system.defaultworkingdirectory)\templates\assets\api.bar

        CALL "C:\Program Files\IBM\ACE\12.0.6.0\ace.cmd" mqsibar --working-directory $(system.defaultworkingdirectory)\ace-projects\TEST_SERVER --bar-file $(system.defaultworkingdirectory)\templates\assets\api_Test.bar
  - task: CmdLine@2
    displayName: "Running tests"
    inputs:
      script: |
        CALL "C:\Program Files\IBM\ACE\12.0.6.0\ace.cmd" IntegrationServer --work-dir $(system.defaultworkingdirectory)\ace-projects\TEST_SERVER --test-project simple-demo_Test --start-msgflows false
    
  - task: JfrogCli@1
    inputs:
      artifactoryService: 'jfrog-service'
      command: 'jfrog rt upload "$(system.defaultworkingdirectory)\templates\assets\api.bar" example-repo-local'

